### PR TITLE
Updated join game url to use new /autojoin endpoint

### PR DESCRIPTION
**Pull request by TypesInCode**

### CODE REVIEW

**Comment by tannerkrewson** [comment]
thanks! so the names seem to be working so that's good! but with this PR, i'm seeing the player be put into different rooms:
Capture

The url of the left iframe is `https://www.qwiqwit.com/autojoin?rocketcrab=true&amp;name=Left&amp;ishost=true` and the right is `https://www.qwiqwit.com/autojoin?rocketcrab=true&amp;name=Right&amp;ishost=false`. If you were expecting `code` to come through, it will not because it must be returned from `getJoinGameUrl`. Is there an API that `getJoinGameUrl` to get a valid game code from your server, or `getJoinGameUrl` could generate a random one?

**Comment by TypesInCode** [comment]
Ah, sorry.  Yeah, ```getJoinGameUrl``` can just create a random code.  Will the client code know to merge the query parameters if ```/autojoin?code=CODE``` is returned?

**Comment by TypesInCode** [comment]
I moved the room code back to the Url and tested.  It should work now.

**Comment by tannerkrewson** [comment]
sorry for the delayed response. i'm still having issues, but i'll go ahead and merge this so we can test on `rocketcrab.com` 👍

**Comment by tannerkrewson** [comment]
Thanks for doing this, by the way! I appreciate it!

live on `rocketcrab.com` pending https://github.com/tannerkrewson/rocketcrab/runs/1099777204

**Comment by TypesInCode** [comment]
Glad to help!  Just tested and it looks good to me.

**Pull request merged**
